VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Diagnostics"
Attribute VB_Description = "Class description goes here"
Attribute VB_GlobalNameSpace = False
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Exxposed = False
Attribute VB_Exxposed = False

Option Explicit

Public Sub Foo()
    Dim i As Long
    While True
        i = i ++ 1
        i = i <> 1
    Wend
End Sub

Sub Identifier()
Attribute Identifier.VB_Description = "Dosctring."
Attribute Identifier.VB_Description = "Dosctring."
'   Dosctring.
'
'   Args:
'       param1:
'
'   Raises:
'
End Sub

Public Enum EnumFoo
    Enum1
    Enum2
    Enum3
End Enum
